./load_targets.sh
./load_diseases.sh
./load_drugs.sh
./load_drugBeta.sh
./load_eco.sh
./load_so.sh
./load_expression.sh
./load_mp.sh
./load_cancerbiomarker.sh
./load_reactome.sh
./load_search.sh
./load_known_drugs.sh
./load_openfda_faers.sh
./load_disease_relation.sh
./load_target_relation.sh
./load_otars.sh
./load_evidences_aotf.sh
./load_interaction.sh
./load_interaction_evidence.sh
