name: Upload

on:
  workflow_call:

jobs:
  gcs:
    name: GCS ☁️
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - name: Prepare the action and log details
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          TAG=$(echo $TAG | sed 's/^v//')
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "The tag for this build is $TAG"
          echo "Github context:\n$GITHUB_CONTEXT"
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: 'open-targets-eu-dev'
          workload_identity_provider: projects/426265110888/locations/global/workloadIdentityPools/github-actions/providers/opentargets
          service_account: github-actions@open-targets-eu-dev.iam.gserviceaccount.com
          access_token_lifetime: 300s
      - uses: actions/download-artifact@v4
        name: Download JAR
        with:
          name: etl-${{ env.TAG }}.jar
      - uses: 'google-github-actions/upload-cloud-storage@v2'
        name: Upload JAR to GCS
        with:
          path: etl-${{ env.TAG }}.jar
          destination: 'opentargets-pipelines/up/etl'
          process_gcloudignore: false
